### ISSUE TITLE
TypeError: concat() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by cap76** [kundajelab/deeplift#70]
Getting an error when trying to follow the examples. I had it working at some point but must have installed an update somewhere, failed to install something, or installed when I shouldn't! Wondering if anyone has encountered the error below. Currently using the Conda install of DeepLift. 

Traceback (most recent call last):
  File "DNAdemo.py", line 118, in <module>
    method_to_model[method_name] = kc.convert_model_from_saved_files('model_7.h5',nonlinear_mxts_mode=nonlinear_mxts_mode)
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/conversion/kerasapi_conversion.py", line 388, in convert_model_from_saved_files
    return model_conversion_function(model_config=model_config, **kwargs) 
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/conversion/kerasapi_conversion.py", line 812, in convert_functional_model
    output_layer.build_fwd_pass_vars()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 174, in build_fwd_pass_vars
    self._build_fwd_pass_vars()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/activations.py", line 34, in _build_fwd_pass_vars
    self._build_fwd_pass_vars_core()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 292, in _build_fwd_pass_vars_core
    self._build_fwd_pass_vars_for_all_inputs()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 383, in _build_fwd_pass_vars_for_all_inputs
    self.inputs.build_fwd_pass_vars(output_layer=self)
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 174, in build_fwd_pass_vars
    self._build_fwd_pass_vars()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 301, in _build_fwd_pass_vars
    self._build_fwd_pass_vars_core()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 292, in _build_fwd_pass_vars_core
    self._build_fwd_pass_vars_for_all_inputs()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 383, in _build_fwd_pass_vars_for_all_inputs
    self.inputs.build_fwd_pass_vars(output_layer=self)
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 174, in build_fwd_pass_vars
    self._build_fwd_pass_vars()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/activations.py", line 34, in _build_fwd_pass_vars
    self._build_fwd_pass_vars_core()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 292, in _build_fwd_pass_vars_core
    self._build_fwd_pass_vars_for_all_inputs()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 383, in _build_fwd_pass_vars_for_all_inputs
    self.inputs.build_fwd_pass_vars(output_layer=self)
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 174, in build_fwd_pass_vars
    self._build_fwd_pass_vars()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 301, in _build_fwd_pass_vars
    self._build_fwd_pass_vars_core()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 292, in _build_fwd_pass_vars_core
    self._build_fwd_pass_vars_for_all_inputs()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 383, in _build_fwd_pass_vars_for_all_inputs
    self.inputs.build_fwd_pass_vars(output_layer=self)
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 174, in build_fwd_pass_vars
    self._build_fwd_pass_vars()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/activations.py", line 34, in _build_fwd_pass_vars
    self._build_fwd_pass_vars_core()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 292, in _build_fwd_pass_vars_core
    self._build_fwd_pass_vars_for_all_inputs()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 383, in _build_fwd_pass_vars_for_all_inputs
    self.inputs.build_fwd_pass_vars(output_layer=self)
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 174, in build_fwd_pass_vars
    self._build_fwd_pass_vars()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 301, in _build_fwd_pass_vars
    self._build_fwd_pass_vars_core()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 292, in _build_fwd_pass_vars_core
    self._build_fwd_pass_vars_for_all_inputs()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 383, in _build_fwd_pass_vars_for_all_inputs
    self.inputs.build_fwd_pass_vars(output_layer=self)
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 174, in build_fwd_pass_vars
    self._build_fwd_pass_vars()
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 304, in _build_fwd_pass_vars
    self._get_input_activation_vars())
  File "/Users/christopherpenfold/Desktop/Code/deeplift/deeplift/layers/core.py", line 628, in _build_activation_vars
    values=input_act_vars)
TypeError: concat() got an unexpected keyword argument 'axis'

**Comment by AvantiShri** [comment]
The line in question reads:
https://github.com/kundajelab/deeplift/blob/9cbe05b212a0ae96f029428507f8433064dccb99/deeplift/layers/core.py#L627-L628
Thus, it looks like the issue is most likely with your version of tensorflow. The latest version of tensorflow has a "concat" operation that takes an axis argument: https://www.tensorflow.org/api_docs/python/tf/concat

What is your tensorflow version? If it's less than 1.7, can you try upgrading it?
